# Generated by Django 6.1.1 on 2026-10-01 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('sign_out', 'Sign out'), ('switched_role', 'Switched role'), ('expired', 'Expired'), ('suspended', 'Suspended')], max_length=16, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_type', models.CharField(choices=[('client', 'Client'), ('bot', 'Bot'), ('staff', 'Staff'), ('system', 'System')], max_length=8)),
                ('entity_type', models.TextField()),
                ('entity_id', models.UUIDField()),
                ('action', models.TextField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('acting_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.membership')),
                ('actor_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.usersession')),
            ],
            options={
                'db_table': 'activity_events',
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='user_sessions_by_user'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='activity_events_timeline'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['acting_membership', 'occurred_at'], name='activity_events_by_member'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_type', 'staff'), _negated=True), models.Q(('acting_membership__isnull', False), ('session__isnull', False)), _connector='OR'), name='activity_staff_needs_role_and_session'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_type', 'client'), _negated=True), ('actor_client__isnull', False), _connector='OR'), name='activity_client_needs_client'),
        ),
    ]
