# Generated by Django 6.1.1 on 2026-10-01 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'case_assignments',
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'case_notes',
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('under_review', 'Under review'), ('referred', 'Referred'), ('accepted', 'Accepted'), ('advocate_assigned', 'Advocate assigned'), ('active', 'Active'), ('closed', 'Closed'), ('referred_back', 'Referred back')], max_length=24, null=True)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('referred', 'Referred'), ('accepted', 'Accepted'), ('advocate_assigned', 'Advocate assigned'), ('active', 'Active'), ('closed', 'Closed'), ('referred_back', 'Referred back')], max_length=24)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'case_status_history',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('given', 'Given'), ('refused', 'Refused')], max_length=8)),
                ('wording_version', models.TextField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'consents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('id_copy', 'ID copy'), ('pml_licence', 'PML licence'), ('eia_certificate', 'EIA certificate'), ('contract', 'Contract'), ('tsa', 'TSA'), ('deed_poll', 'Deed poll'), ('gazette_notice', 'Gazette notice'), ('will', 'Will'), ('letter', 'Letter'), ('business_licence', 'Business licence'), ('practising_certificate', 'Practising certificate'), ('other', 'Other')], default='other', max_length=32)),
                ('visibility', models.CharField(choices=[('clc_only', 'CLC only'), ('shared_with_firm', 'Shared with firm')], default='shared_with_firm', max_length=24)),
                ('file_name', models.TextField()),
                ('mime_type', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('storage_key', models.TextField(unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('consent_requested', 'Consent requested'), ('consent_refused', 'Consent refused'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('returned', 'Returned'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='consent_requested', max_length=24)),
                ('consent_requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_confirmed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'referral_documents',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.TextField(unique=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web'), ('email', 'Email'), ('phone', 'Phone'), ('walk_in', 'Walk-in')], default='whatsapp', max_length=16)),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('zh', 'Chinese')], default='sw', max_length=2)),
                ('region', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('referred', 'Referred'), ('accepted', 'Accepted'), ('advocate_assigned', 'Advocate assigned'), ('active', 'Active'), ('closed', 'Closed'), ('referred_back', 'Referred back')], default='new', max_length=24)),
                ('ready_to_close_at', models.DateTimeField(blank=True, null=True)),
                ('ready_to_close_summary', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('withdrawn_by_client', 'Withdrawn by client'), ('not_taken', 'Not taken'), ('no_firm_available', 'No firm available')], max_length=24, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'db_table': 'cases',
            },
        ),
    ]
