# Generated by Django 6.1.1 on 2026-10-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        ('conversations', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='case',
            name='current_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='case',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='consent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='clients.client'),
        ),
        migrations.AddField(
            model_name='consent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='referral',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='cases.case'),
        ),
        migrations.AddField(
            model_name='referral',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='referral',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='consent',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consent', to='cases.referral'),
        ),
        migrations.AddField(
            model_name='referraldocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.document'),
        ),
        migrations.AddField(
            model_name='referraldocument',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.referral'),
        ),
        migrations.AddField(
            model_name='referral',
            name='documents',
            field=models.ManyToManyField(related_name='referrals', through='cases.ReferralDocument', to='cases.document'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'updated_at'], name='cases_by_status'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_firm', 'status'], name='cases_by_firm'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), models.Q(('outcome__isnull', False), ('closed_at__isnull', False)), _connector='OR'), name='cases_closed_needs_outcome'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['referred', 'accepted', 'advocate_assigned', 'active']), _negated=True), ('current_firm__isnull', False), _connector='OR'), name='cases_with_firm_when_referred'),
        ),
        migrations.AddConstraint(
            model_name='caseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('case',), name='case_assignments_one_current'),
        ),
        migrations.AddIndex(
            model_name='casestatushistory',
            index=models.Index(fields=['case', 'changed_at'], name='case_status_history_case'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='documents_by_case'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='documents_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('case__isnull', False), ('organization__isnull', False), _connector='OR'), name='documents_case_or_org'),
        ),
        migrations.AddConstraint(
            model_name='referraldocument',
            constraint=models.UniqueConstraint(fields=('referral', 'document'), name='referral_documents_pk'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['firm', 'status'], name='referrals_firm_inbox'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'accepted'), _negated=True), ('conflict_confirmed', True), _connector='OR'), name='referrals_accept_needs_conflict_check'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['declined', 'returned', 'withdrawn']), _negated=True), ('reason__isnull', False), _connector='OR'), name='referrals_end_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['consent_requested', 'sent', 'accepted'])), fields=('case',), name='referrals_one_live'),
        ),
    ]
