# Generated by Django 6.1.1 on 2026-10-01 13:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('phone_e164', models.TextField(blank=True, null=True, unique=True)),
                ('wa_id', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('zh', 'Chinese')], default='sw', max_length=2)),
                ('region', models.TextField(blank=True, null=True)),
                ('privacy_notice_version', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'constraints': [models.CheckConstraint(condition=models.Q(('phone_e164__isnull', False), ('wa_id__isnull', False), _connector='OR'), name='clients_phone_or_wa_id')],
            },
        ),
    ]
