# Generated by Django 6.1.1 on 2026-10-01 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('holiday_date', models.DateField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'public_holidays',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name_sw', models.TextField()),
                ('name_en', models.TextField()),
                ('name_zh', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('weekday', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'office hours',
                'db_table': 'office_hours',
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='office_hours_weekday_range'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='office_hours_closes_after_opens')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField()),
                ('year', models.SmallIntegerField()),
                ('last_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'reference_counters',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='reference_counters_pk')],
            },
        ),
    ]
