# Generated by Django 6.1.1 on 2026-10-02 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bot_settings",
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document")],
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("storage_key", models.CharField(max_length=300)),
                ("sha256", models.CharField(max_length=64)),
                ("meta_media_id", models.CharField(blank=True, max_length=64)),
                ("meta_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_media_assets",
                "ordering": ["name"],
            },
        ),
    ]
