# Generated by Django 6.1.1 on 2026-10-01 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('is_entry_flow', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
            options={
                'db_table': 'bot_flows',
            },
        ),
        migrations.CreateModel(
            name='BotFlowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('definition', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='conversations.botflow')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'db_table': 'bot_flow_versions',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('handoff', 'Handoff'), ('timeout', 'Timeout'), ('abandoned', 'Abandoned')], max_length=16, null=True)),
                ('flow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conversations.botflowversion')),
            ],
            options={
                'db_table': 'bot_sessions',
            },
        ),
        migrations.CreateModel(
            name='BotSessionStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_id', models.TextField()),
                ('client_input', models.TextField(blank=True, null=True)),
                ('bot_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='conversations.botsession')),
            ],
            options={
                'db_table': 'bot_session_steps',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web'), ('email', 'Email'), ('phone', 'Phone'), ('walk_in', 'Walk-in')], default='whatsapp', max_length=16)),
                ('status', models.CharField(choices=[('bot', 'Bot'), ('queued', 'Queued'), ('with_staff', 'With staff'), ('closed', 'Closed')], default='bot', max_length=16)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='clients.client')),
                ('taken_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.AddField(
            model_name='botsession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bot_sessions', to='conversations.conversation'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('bot', 'Bot'), ('staff', 'Staff'), ('system', 'System')], max_length=8)),
                ('type', models.CharField(choices=[('text', 'Text'), ('interactive', 'Interactive'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('location', 'Location'), ('system', 'System')], default='text', max_length=16)),
                ('body', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.TextField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=16)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='conversations.conversation')),
                ('sent_as_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageStatusEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='conversations.message')),
            ],
            options={
                'db_table': 'message_status_events',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('zh', 'Chinese')], max_length=2)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('meta_template_id', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused')], default='draft', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_templates',
                'constraints': [models.UniqueConstraint(fields=('name', 'language'), name='message_templates_name_lang_uq')],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.messagetemplate'),
        ),
        migrations.AddConstraint(
            model_name='botflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_entry_flow', True)), fields=('is_entry_flow',), name='bot_flows_one_entry'),
        ),
        migrations.AddConstraint(
            model_name='botflowversion',
            constraint=models.UniqueConstraint(fields=('flow', 'version'), name='bot_flow_versions_flow_version_uq'),
        ),
        migrations.AddConstraint(
            model_name='botflowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('flow',), name='bot_flow_versions_one_live'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'closed'), _negated=True), fields=('client', 'channel'), name='conversations_one_open'),
        ),
        migrations.AddConstraint(
            model_name='botsession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('conversation',), name='bot_sessions_one_active'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_by_conversation'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender_type', 'staff'), _negated=True), ('sent_as_membership__isnull', False), _connector='OR'), name='messages_staff_needs_membership'),
        ),
    ]
