# Generated by Django 6.1.1 on 2026-10-02 04:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_conversation", "New conversation"),
                            ("keyword", "Keyword or link code"),
                        ],
                        max_length=24,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "flow_triggers",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="botflow",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="botflow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="botflowversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="botflowversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="botsession",
            name="last_step_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="botsession",
            name="stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="botflowversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("flow",),
                name="bot_flow_versions_one_draft",
            ),
        ),
        migrations.AddField(
            model_name="flowtrigger",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggers",
                to="conversations.botflow",
            ),
        ),
    ]
