# Generated by Django 6.1.1 on 2026-10-01 13:55

import accounts.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_e164', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FirmService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
            options={
                'db_table': 'firm_services',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('clc', 'CLC'), ('law_firm', 'Law firm')], max_length=16)),
                ('name', models.TextField()),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('tin', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('regions_served', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_e164', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(related_name='firms', through='accounts.FirmService', to='core.service')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('clc_admin', 'CLC Admin'), ('firm_admin', 'Firm Admin'), ('advocate', 'Advocate')], max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='invited', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.organization')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.AddField(
            model_name='firmservice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='advocate_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_number', models.TextField(unique=True)),
                ('practising_certificate', models.TextField(blank=True, null=True)),
                ('certificate_expires_on', models.DateField(blank=True, null=True)),
                ('platform_suspended_at', models.DateTimeField(blank=True, null=True)),
                ('platform_suspended_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'advocate_profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('platform_suspended_at__isnull', True), ('platform_suspended_reason__isnull', False), _connector='OR'), name='advocate_suspension_reason_required')],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'clc')), fields=('type',), name='organizations_one_clc'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['rejected', 'suspended']), _negated=True), ('status_reason__isnull', False), _connector='OR'), name='organizations_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'role'), name='memberships_user_org_role_uq'),
        ),
        migrations.AddConstraint(
            model_name='firmservice',
            constraint=models.UniqueConstraint(fields=('organization', 'service'), name='firm_services_pk'),
        ),
    ]
