// The five CLC service packages. Each keeps its original language as the default,
// with translations available through the in-section language tabs.
export const WHATSAPP = '255745118253'
export const waLink = (text) => `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`

export const services = [
  {
    id: 'mchimbaji-mwekezaji',
    native: 'sw',
    theme: 'sand',
    icon: 'pickaxe',
    image: '/images/mining.jpg',
    inset: '/images/gold.jpg',
    short: { sw: 'Mchimbaji & Mwekezaji', en: 'Miner & Investor TSA', zh: '矿工与投资者协议' },
    blurb: { sw: 'Mikataba salama kati ya wachimbaji wadogo na wawekezaji.', en: 'Secure agreements between small-scale miners and investors.', zh: '小型矿工与投资者之间的安全协议。' },
    watermark: { sw: 'Rasilimali Zetu. Utaalamu Wetu.', en: "Tanzania's Resources. Our Expertise.", zh: '坦桑资源，专业护航。' },
    badge: { sw: 'Leseni ya PML', en: 'PML Licence', zh: 'PML 许可证' },
    title: {
      sw: 'Mkataba kati ya Mchimbaji Mdogo na Mwekezaji',
      en: 'Agreement between a Small-Scale Miner and an Investor',
      zh: '小型矿工与投资者之间的协议',
    },
    intro: {
      sw: 'Sheria za madini za Tanzania zinawawezesha wachimbaji wadogo kunufaika na rasilimali zao na kushirikiana na wawekezaji kwa njia salama na halali kupitia Makubaliano ya Msaada wa Kiufundi (TSA).',
      en: "Tanzania's mining laws empower small-scale miners to benefit from their resources and partner with investors safely and lawfully through a Technical Support Agreement (TSA).",
      zh: '坦桑尼亚矿业法使小型矿工能够从自身资源中受益，并通过技术支持协议（TSA）安全合法地与投资者合作。',
    },
    items: {
      sw: ['Uhakiki wa Leseni Ndogo ya Uchimbaji (PML)', 'Uandishi/uhakiki wa mikataba na wenye maduara', 'Kuratibu Scoping Report au uhakiki wa Cheti cha EIA', 'Mipango mitano ya uendeshaji wa mgodi', 'Nyaraka za vikundi/vyama vya ushirika', 'Uhakiki wa nyaraka za mwekezaji na mmiliki', 'Uandishi na kusaini Mkataba wa TSA', 'Kuwasilisha maombi ya TSA', 'Ufuatiliaji hadi uidhinishaji'],
      en: ['Primary Mining Licence (PML) verification', 'Contracts between licence holder and pit owners', 'Scoping Report facilitation or EIA review', 'Five mining operational plans', 'Group & cooperative legal documents', 'Investor & licence-holder document review', 'Drafting & signing of the TSA', 'TSA application submission', 'Follow-up to final approval'],
      zh: ['初级采矿许可证（PML）核实', '许可证持有人与矿坑所有者合同', '范围界定报告或环评证书审核', '五项采矿运营计划', '团体与合作社法律文件', '投资者与持证人文件审核', '起草并签署技术支持协议', '提交 TSA 申请', '跟进至最终审批'],
    },
    steps: { sw: ['Uhakiki wa PML', 'Mkataba wa TSA', 'Uidhinishaji'], en: ['PML check', 'TSA drafting', 'Approval'], zh: ['许可证核实', 'TSA 起草', '审批'] },
    wa: { sw: 'Nataka huduma ya Mkataba kati ya Mchimbaji Mdogo na Mwekezaji', en: 'I want help with a small-scale miner & investor agreement', zh: '我需要小型矿工与投资者协议服务' },
    cta: { sw: 'Pata Huduma Hii', en: 'Get This Service', zh: '获取此服务' },
  },
  {
    id: 'invest-in-gold',
    native: 'en',
    theme: 'ocean',
    icon: 'globe',
    image: '/images/dar.jpg',
    inset: '/images/handshake.jpg',
    short: { sw: 'Uwekezaji wa Kigeni', en: 'Foreign Investment', zh: '外国投资' },
    blurb: { sw: 'Shirikiana na mchimbaji wa Kitanzania kisheria.', en: 'Partner with a Tanzanian miner — legally.', zh: '合法地与坦桑尼亚矿工合作。' },
    watermark: { sw: 'Uwekezaji Wako. Kipaumbele Chetu.', en: 'Your Investment. Our Priority.', zh: '您的投资，我们的首要任务。' },
    badge: { sw: 'Cap 123 • Kif. 8(3)', en: 'Cap 123 • S. 8(3)', zh: '第123章 • 第8(3)条' },
    title: {
      sw: 'Jinsi ya Kushirikiana na Mchimbaji wa Kitanzania na Kuwekeza kwenye Dhahabu — Kisheria',
      en: 'How to Partner with a Tanzanian Miner & Invest in Gold — Legally',
      zh: '如何合法地与坦桑尼亚矿工合作并投资黄金',
    },
    intro: {
      sw: 'TSA inampa mwekezaji wa kigeni mfumo halali wa kushirikiana na wamiliki wa PML, kwa mujibu wa Kifungu 8(3) cha Sheria ya Madini, Sura 123 (2019).',
      en: 'The Technical Support Agreement (TSA) gives foreign investors a legal framework to partner with PML holders, in compliance with Section 8(3) of the Mining Act, Cap 123 (2019).',
      zh: '技术支持协议（TSA）为外国投资者提供与 PML 持有人合作的合法框架，符合《2019年矿业法》第123章第8(3)条。',
    },
    items: {
      sw: ['Uhakiki wa PML', 'Mikataba kati ya mmiliki wa PML na wachimbaji', 'Scoping Report au uhakiki wa EIA', 'Mipango mitano ya uendeshaji', 'Nyaraka za vikundi/ushirika', 'Uhakiki na ukusanyaji wa nyaraka', 'Uandishi na utekelezaji wa TSA', 'Mwongozo wa kuwasilisha maombi', 'Ufuatiliaji hadi uidhinishaji'],
      en: ['PML verification', 'Contract preparation & review', 'Scoping Report or EIA Certificate review', 'Five mining operational plans', 'Group & cooperative documents', 'Investor & licence-holder document review', 'Drafting & execution of the TSA', 'Guidance on application submission', 'Approval follow-up to completion'],
      zh: ['PML 许可证核实', '合同起草与审核', '范围界定报告或环评证书审核', '五项采矿运营计划', '团体与合作社文件', '投资者与持证人文件审核', '起草并执行 TSA', '申请提交指导', '跟进直至审批完成'],
    },
    steps: { sw: ['Uhakiki', 'Mkataba', 'Tume ya Madini'], en: ['Due diligence', 'TSA contract', 'Mining Commission'], zh: ['尽职调查', 'TSA 合同', '矿业委员会'] },
    wa: { sw: 'Nataka msaada wa uwekezaji halali kwenye dhahabu Tanzania', en: 'I want help with legal gold mining investment in Tanzania', zh: '我需要坦桑尼亚黄金投资的法律帮助' },
    cta: { sw: 'Pata Huduma Hii', en: 'Get Service Now', zh: '立即获取服务' },
  },
  {
    id: 'huangjin-touzi',
    native: 'zh',
    theme: 'crimson',
    icon: 'landmark',
    image: '/images/gold.jpg',
    inset: '/images/building.jpg',
    short: { sw: 'Wawekezaji wa China', en: 'For Chinese Investors', zh: '中国投资者专区' },
    blurb: { sw: 'Huduma kamili kwa Kichina kwa wawekezaji wa dhahabu.', en: 'Full service in Chinese for gold investors.', zh: '为黄金投资者提供全中文服务。' },
    watermark: { sw: 'Dhahabu. Kisheria. Salama.', en: 'Gold. Legal. Secure.', zh: '黄金 · 合法 · 安全' },
    badge: { sw: 'Huduma kwa 中文', en: 'Service in 中文', zh: '全程中文服务' },
    title: {
      sw: 'Njia Halali ya Kuwekeza kwenye Dhahabu bila Leseni Yako Mwenyewe',
      en: 'The Legal Route to Invest in Gold Mining Without Your Own Licence',
      zh: '无需自持许可证即可合法投资黄金矿业',
    },
    intro: {
      sw: 'Kupitia TSA, mwekezaji anashirikiana na mmiliki wa PML kwa uhalali kamili. Timu yetu inakuhudumia kwa Kichina kuanzia mwanzo hadi mwisho.',
      en: 'Through a TSA, investors partner lawfully with a PML holder. Our team supports you in Chinese from start to finish.',
      zh: '坦桑尼亚的技术支持协议（TSA）提供了合法框架，允许外国投资者与初级采矿许可证（PML）持有者合作，并符合《2019年矿业法》第123章第8(3)条的规定。',
    },
    items: {
      sw: ['Uhakiki wa PML', 'Mikataba ya mmiliki na wachimbaji', 'Scoping Report / EIA', 'Mipango ya uendeshaji wa mgodi', 'Nyaraka za vikundi/ushirika', 'Uhakiki wa nyaraka za mwekezaji', 'Uandishi na utekelezaji wa TSA', 'Kuwasilisha maombi Tume ya Madini', 'Ufuatiliaji hadi uidhinishaji'],
      en: ['PML verification', 'Holder & miner contracts', 'Scoping Report / EIA review', 'Mining operational plans', 'Group & cooperative documents', 'Investor document review', 'Drafting & executing the TSA', 'Submission to the Mining Commission', 'Follow-up to approval'],
      zh: ['初级采矿许可证的核实', '起草或审核持证人与小型矿工的合同', '协助获取范围界定报告或审核环评证书', '协助准备采矿运营计划', '起草并核实合作社或团体法律文件', '审核投资者和许可证持有人的文件', '起草并执行技术支持协议', '协助向矿业委员会提交申请', '跟进并完成审批流程'],
    },
    steps: { sw: ['Ushauri', 'TSA', 'Uidhinishaji'], en: ['Consult', 'TSA', 'Approval'], zh: ['咨询', '签署协议', '审批'] },
    wa: { sw: 'Nahitaji msaada wa uwekezaji wa dhahabu (kwa Kichina)', en: 'I need legal help with gold mining investment (Chinese)', zh: '我需要黄金矿业投资的法律帮助' },
    cta: { sw: 'Pata Huduma Hii', en: 'Get Service Now', zh: '立即获取服务' },
  },
  {
    id: 'deed-poll',
    native: 'sw',
    theme: 'peach',
    icon: 'scroll',
    image: '/images/deed.jpg',
    inset: '/images/idcard.jpg',
    short: { sw: 'Deed Poll & Jina', en: 'Deed Poll & Name Change', zh: '契据更名' },
    blurb: { sw: 'Badilisha jina lako kisheria na kwa usalama.', en: 'Change your name legally and securely.', zh: '合法安全地更改姓名。' },
    watermark: { sw: 'Jina Lako. Utambulisho Wako.', en: 'Your Name. Your Future.', zh: '您的名字，您的未来。' },
    badge: { sw: 'Wiki 1–2', en: '1–2 weeks', zh: '1–2 周' },
    title: {
      sw: 'Badilisha Jina Kisheria — Kwa Deed Poll / Kiapo cha Majina',
      en: 'Change Your Name Legally — By Deed Poll',
      zh: '通过契据（Deed Poll）合法更改姓名',
    },
    intro: {
      sw: 'Una changamoto ya majina kwenye vitambulisho vyako? Tunaandaa Deed Poll rasmi, kuisajili serikalini na kuitangaza kwenye Gazeti la Serikali kama sheria inavyotaka.',
      en: 'Name mismatch on your IDs? We prepare an official Deed Poll, register it with the government and publish it in the Government Gazette as the law requires.',
      zh: '证件上的姓名不一致？我们为您准备正式的更名契据，完成政府注册并按法律要求在政府公报上公告。',
    },
    items: {
      sw: ['Kupitia nyaraka zako kwa umakini', 'Ushauri na Wakili aliyeidhinishwa', 'Kuandaa Deed Poll rasmi', 'Usajili Wizara ya Ardhi', 'Tangazo kwenye Gazeti la Serikali', 'Barua rasmi kwenda NIDA', 'Kurekebisha majina kwa Mafao ya NSSF'],
      en: ['Careful review of your documents', 'Consultation with a licensed advocate', 'Preparation of an official Deed Poll', 'Registration at the Ministry of Lands', 'Publication in the Government Gazette', 'Official letter to NIDA', 'Name correction for NSSF benefits'],
      zh: ['仔细审阅您的文件', '与持牌律师咨询', '起草正式更名契据', '在土地部注册', '在政府公报上公告', '致国家身份局（NIDA）正式函件', '为 NSSF 福利更正姓名'],
    },
    steps: { sw: ['Deed Poll', 'Usajili', 'Gazeti & NIDA'], en: ['Deed Poll', 'Registration', 'Gazette & NIDA'], zh: ['更名契据', '注册', '公报与 NIDA'] },
    wa: { sw: 'Nataka huduma ya kubadilisha jina kisheria kwa Deed Poll', en: 'I want to change my name legally by Deed Poll', zh: '我想通过契据合法更改姓名' },
    cta: { sw: 'Pata Huduma Hii', en: 'Get This Service', zh: '获取此服务' },
  },
  {
    id: 'wosia',
    native: 'sw',
    theme: 'mint',
    icon: 'shield',
    image: '/images/family.jpg',
    inset: '/images/will.jpg',
    short: { sw: 'Wosia & Urithi', en: 'Wills & Inheritance', zh: '遗嘱与继承' },
    blurb: { sw: 'Linda urithi wako na wapendwa wako.', en: 'Protect your legacy and loved ones.', zh: '保护您的遗产与家人。' },
    watermark: { sw: 'Linda Kilicho Muhimu.', en: 'Protect What Matters Most.', zh: '守护最重要的一切。' },
    badge: { sw: 'Wosia PDF — BURE', en: 'Will PDF — FREE', zh: '遗嘱模板 — 免费' },
    title: {
      sw: 'Andika Wosia — Usiache Migogoro',
      en: 'Write Your Will — Leave No Disputes',
      zh: '订立遗嘱——不留纷争',
    },
    intro: {
      sw: 'Umejenga mali zako kwa juhudi kubwa — usiache urithi wako uingie kwenye migogoro. Andika wosia haraka, salama, kwa mwongozo wa wakili mwenye uzoefu wa mirathi.',
      en: "You worked hard to build your assets — don't let your legacy end in disputes. Write your will quickly and safely with an experienced inheritance advocate.",
      zh: '您辛苦积累的财富，不应让遗产陷入纷争。在经验丰富的继承律师指导下，快速安全地订立遗嘱。',
    },
    items: {
      sw: ['Nakala ya Wosia (PDF) — Bure', 'Kuandikiwa Wosia na Wakili', 'Ushauri kupitia Simu au WhatsApp', 'Uhakiki wa Wosia kabla ya kusaini', 'Ushauri wa mahali salama pa kuhifadhi'],
      en: ['Will template (PDF) — Free', 'Will drafted by an advocate', 'Advice by phone or WhatsApp', 'Review before signing', 'Guidance on safe storage'],
      zh: ['遗嘱模板（PDF）— 免费', '由律师起草遗嘱', '电话或 WhatsApp 咨询', '签署前审核', '安全保管建议'],
    },
    steps: { sw: ['Ushauri', 'Uandishi', 'Kusaini'], en: ['Consult', 'Drafting', 'Signing'], zh: ['咨询', '起草', '签署'] },
    wa: { sw: 'Nataka huduma ya kuandika wosia kisheria', en: 'I want help writing my will', zh: '我需要订立遗嘱的帮助' },
    cta: { sw: 'Pata Huduma Hii', en: 'Get This Service', zh: '获取此服务' },
  },
]

export const testimonials = [
  {
    name: 'Johnson Laiton Ulaya',
    role: { sw: 'Wakili wa Mahakama Kuu, Dar es Salaam', en: 'Advocate of the High Court of Tanzania, Dar es Salaam', zh: '坦桑尼亚高等法院律师，达累斯萨拉姆' },
    photo: 'https://clc.tz/assets/johnson.png',
    quote: {
      en: 'Joining the Community Legal Clinic platform gave me access to international clients looking for legitimate partnerships in Tanzania’s mining sector. The system is transparent and well-organized, and it helped me grow my practice.',
      sw: 'Kujiunga na CLC kulinipa wateja wa kimataifa wanaotafuta ushirikiano halali kwenye sekta ya madini Tanzania. Mfumo ni wa uwazi, umepangwa vizuri, na umenisaidia kukuza kazi yangu.',
      zh: '加入 CLC 平台让我接触到寻求坦桑尼亚矿业合法合作的国际客户。系统透明、组织良好，帮助我发展了业务。',
    },
  },
  {
    name: 'Ezekiel Hamis Mohamed',
    role: { sw: 'Mkurugenzi, SELEAD Tanzania Limited, Mwanza', en: 'Director, SELEAD Tanzania Limited, Mwanza', zh: 'SELEAD Tanzania Limited 董事，姆万扎' },
    photo: 'https://clc.tz/assets/ezekiel.png',
    quote: {
      en: 'Navigating Tanzania’s mining regulations as a foreign investor seemed daunting until I discovered CLC. Their licensed practitioners handled the entire registration with the Mining Commission. Within weeks, we had all our permits.',
      sw: 'Kanuni za madini zilionekana ngumu hadi nilipogundua CLC. Mawakili wao walishughulikia usajili wote na Tume ya Madini. Ndani ya wiki chache tulipata vibali vyote.',
      zh: '作为外国投资者，坦桑尼亚矿业法规曾令人望而生畏，直到我发现了 CLC。他们的持牌律师处理了矿业委员会的全部注册，几周内我们就拿到了所有许可证。',
    },
  },
  {
    name: 'Feith Moses Livingstone',
    role: { sw: 'Mjasiriamali, Dodoma', en: 'Entrepreneur, Dodoma', zh: '企业家，多多马' },
    photo: 'https://clc.tz/assets/feith.png',
    quote: {
      en: 'I needed to legally change my name, and CLC made it incredibly straightforward. The deed poll was professionally drafted and submitted to the Ministry of Lands the same day, and registered within one to two weeks.',
      sw: 'Nilihitaji kubadilisha jina kisheria, na CLC walifanya iwe rahisi sana. Deed Poll iliandaliwa kitaalamu na kuwasilishwa Wizara ya Ardhi siku hiyo hiyo, ikasajiliwa ndani ya wiki 1–2.',
      zh: '我需要合法更改姓名，CLC 让整个过程非常简单。更名契据当天即专业起草并提交至土地部，并在一到两周内完成注册。',
    },
  },
]
